
const main=document.querySelector('#main');
const dialog=document.querySelector('#editor');
const state={objects:[],fields:[],workflows:[],objectTypes:{},session:null,overview:null,selected:new Set(),token:'',search:''};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pretty=v=>String(v??'').replaceAll('_',' ');
const badge=(v,label)=>'<span class="badge '+esc(v)+'">'+esc(label||pretty(v))+'</span>';
const date=v=>v?new Date(v).toLocaleDateString(undefined,{day:'numeric',month:'short',year:'numeric'}):'Not recorded';
const link=(uri,label)=>{try{const u=new URL(uri);return ['http:','https:'].includes(u.protocol)?'<a href="'+esc(u.href)+'" target="_blank" rel="noopener noreferrer">'+esc(label||uri)+'</a>':esc(label||uri)}catch{return esc(label||uri)}};
const key=()=>crypto.randomUUID();
const products=()=>state.objects.filter(o=>o.object_type==='product');
const objectsOf=t=>state.objects.filter(o=>o.object_type===t);
const get=id=>state.objects.find(o=>o.object_id===id);
const fieldDef=k=>state.fields.find(f=>f.key===k);
const valueText=f=>f?.value===null||f?.value===undefined?'Unknown':String(f.value);
function toast(message,error=false){const el=document.querySelector('#notice');el.textContent=message;el.classList.toggle('error',error);el.hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.hidden=true,6500)}
async function api(path,options={}){
 const headers={'Content-Type':'application/json','X-Workspace-Action':'1',...(state.token?{'X-BS-CATS-Key':state.token}:{}),...options.headers};
 const response=await fetch('/v1'+path,{...options,headers});
 const data=await response.json();
 if(!response.ok)throw new Error(Array.isArray(data.detail)?data.detail.map(x=>x.msg).join('; '):data.detail||'Request failed');
 return data;
}
async function reload(){
 [state.objects,state.overview]=await Promise.all([api('/objects'),api('/overview')]);
 const schema=await api('/schema');state.fields=schema.fields;state.workflows=schema.workflows;state.objectTypes=schema.object_types||{};
 state.selected=new Set([...state.selected].filter(id=>get(id)));await render();
}
function heading(eyebrow,title,description,action=''){return '<div class="page-head"><div><div class="eyebrow">'+esc(eyebrow)+'</div><h1>'+esc(title)+'</h1><p class="lede">'+esc(description)+'</p></div>'+action+'</div>'}
function empty(title,body){return '<div class="empty"><h2>'+esc(title)+'</h2><p>'+esc(body)+'</p></div>'}
function sourcesHTML(item){return '<ul class="source-list">'+item.sources.map(s=>'<li>'+link(s.uri,s.title||s.publisher||s.uri)+'<small>'+esc(s.publisher)+' / observed '+date(s.captured_at)+'</small></li>').join('')+'</ul>'}
function productCard(p){const known=Object.values(p.payload.fields||{}).filter(f=>f.value!==null).length;return '<article class="card product-card"><div class="card-top"><span class="eyebrow">'+esc(p.payload.brand)+'</span>'+badge(p.status,p.status==='active'?'Reviewed':'Needs review')+'</div><h3>'+esc(p.title)+'</h3><p>'+esc(p.payload.buyer_job)+'</p><div class="mini-fields">'+['fov_deg','refresh_hz','weight_g'].map(k=>'<div><span>'+esc(fieldDef(k)?.label||pretty(k))+'</span><strong>'+esc(valueText(p.payload.fields?.[k]))+(p.payload.fields?.[k]?.value!=null?' '+esc(fieldDef(k)?.unit||''):'')+'</strong></div>').join('')+'</div><p>'+known+' sourced fields / '+esc(p.payload.market)+'</p><div class="card-bottom"><a href="#object/'+encodeURIComponent(p.object_id)+'">Open evidence &rarr;</a><label class="checkbox"><input type="checkbox" data-compare="'+esc(p.object_id)+'" '+(state.selected.has(p.object_id)?'checked':'')+'>Compare</label></div></article>'}
function recordLink(o){return '#object/'+encodeURIComponent(o.object_id)}
function stale(o){if(o.object_type==='storyboard'){const brief=get(o.payload.brief_object_id);return !brief||brief.version!==o.payload.brief_version||stale(brief)}if(o.object_type==='refresh_job')return get(o.payload.source_policy_id)?.version!==o.payload.source_policy_version;return Object.entries(o.payload?.input_versions||o.metadata?.source_versions||{}).some(([id,version])=>get(id)?.version!==version)}
function overview(){
 const o=state.overview;
 return heading('THE OPERATING DESK','A clearer view of smart glasses.','One place to collect evidence, compare useful differences and turn research into original content.')+
 '<section class="hero"><div><div class="eyebrow">CURRENT FOCUS / ONLINE BUYERS</div><h2>Start with the job.<br>Then find the glasses.</h2><p>Build a useful, manageable catalogue. Keep regional details visible and every claim connected to its evidence.</p><a href="#catalogue">Explore the research &rarr;</a></div><div><svg class="hero-art" viewBox="0 0 360 180" aria-label="Illustration of glasses, not a specific product" role="img"><g fill="none" stroke="currentColor" stroke-width="5"><path d="M55 67L21 31M301 67l34-36M139 78q39-24 79 0"/><path d="M48 67q44-16 101 0l-9 57q-29 26-73 2Z"/><path d="M211 67q44-16 101 0l-18 59q-43 21-74-2Z"/><path d="M72 75l51 45M85 75l38 34M238 75l49 45" stroke-width="1" opacity=".3"/></g></svg><p class="art-caption">ORIGINAL ILLUSTRATION / NOT PRODUCT PHOTOGRAPHY</p></div></section>'+
 '<section class="stats"><div class="stat"><strong>'+o.products+'</strong><span>Product records</span><small>Coverage grows with evidence</small></div><div class="stat"><strong>'+o.review_pending+'</strong><span>Awaiting a decision</span><small>Grouped in your review inbox</small></div><div class="stat"><strong>'+o.fields+'</strong><span>Shared field definitions</span><small>Forms follow the same meanings</small></div><div class="stat"><strong>$80</strong><span>Reported subscription cost</span><small>Other charges unreconciled / $500 ceiling</small></div></section>'+
 '<div class="section-row"><h2>The current research</h2><a href="#catalogue">All products &rarr;</a></div><div class="grid">'+products().slice(0,3).map(productCard).join('')+'</div>'+
 '<div class="grid two section-row"><section class="card"><div class="eyebrow">NEXT USEFUL DECISION</div><h3>Connect value to an online purchase.</h3><p class="small muted">Checkout access, affiliate eligibility and collected revenue are different steps. See the current evidence and outstanding gaps.</p><a class="small" href="#commerce">Inspect revenue paths &rarr;</a></section><section class="card"><div class="eyebrow">THE SYSTEM LEARNS WITH YOU</div><h3>Feedback becomes a traceable decision.</h3><p class="small muted">Capture a correction or useful preference and link it to a proposed improvement and an evaluation.</p><a class="small" href="#learning">Open feedback &rarr;</a></section></div>';
}
function catalogue(){return heading('THE EVIDENCE BASE','Product catalogue','Manufacturer-stated records with sources, fit conditions and explicit unknowns. This initial sample is not a complete market survey.','<button data-action="new-product">Add product</button>')+'<div class="filters"><input id="catalogue-search" type="search" aria-label="Search products" placeholder="Search products, brands or buyer jobs" value="'+esc(state.search)+'"><a href="#compare">Compare selected ('+state.selected.size+')</a></div><div class="grid" id="product-grid">'+products().filter(p=>JSON.stringify([p.title,p.payload.brand,p.payload.buyer_job]).toLowerCase().includes(state.search.toLowerCase())).map(productCard).join('')+'</div>'}
function compare(){const rows=products().filter(p=>state.selected.has(p.object_id));if(rows.length<2)return heading('MATCHED DECISIONS','Compare the things that matter.','Choose at least two records in the catalogue.')+empty('Build your comparison','Select the Compare checkbox on product cards, then return here.')+'<p><a href="#catalogue">Choose products &rarr;</a></p>';
 const same=new Set(rows.map(p=>p.payload.category)).size===1;
 return heading('SIDE BY SIDE','A comparison with its limits intact.','Missing is not false. Check measurement conditions and regional variants before treating figures as equivalent.')+(!same?'<div class="callout">These products serve different categories. A numeric winner would be misleading.</div>':'')+'<div class="table-wrap"><table><thead><tr><th>Field</th>'+rows.map(p=>'<th><a href="'+recordLink(p)+'">'+esc(p.title)+'</a><br>'+esc(p.payload.market)+'</th>').join('')+'</tr></thead><tbody>'+state.fields.filter(f=>rows.some(p=>p.payload.fields?.[f.key]?.value!=null)).map(f=>'<tr><td>'+esc(f.label)+'<small>'+esc(f.description)+'</small></td>'+rows.map(p=>{const a=p.payload.fields?.[f.key];return '<td>'+esc(valueText(a))+(a?.value!=null?' '+esc(f.unit||''):'')+'<small>'+esc(a?.conditions||'No observation recorded')+'</small>'+((a?.source_ids||[]).map(id=>{const s=p.sources.find(s=>s.source_id===id);return s?'<small>'+link(s.uri,s.publisher||'Source')+'</small>':''}).join(''))+'</td>'}).join('')+'</tr>').join('')+'</tbody></table></div>';
}
function humanReviewRoute(o){const p=o.payload||{},t=String(o.object_type||'').toLowerCase(),reserved={publication_request:'Publication',publication_decision:'Publication',release_authorization:'Publication',spend_authorization:'Financial',budget_change:'Financial',credential_transfer:'Security',account_consent:'Account',contract_acceptance:'Legal'};if(reserved[t])return{required:true,category:reserved[t],reason:'Reserved human authority'};if(p.human_review_required===true)return{required:true,category:pretty(p.review_category||'explicit_exception'),reason:p.review_reason||'Workflow exception'};const kind=[p.decision_type,p.kind,p.proposal_type,p.change_class].filter(Boolean).join(' ').toLowerCase();if(/publish|release_authorization|spend|budget_increase|contract|credential/.test(kind))return{required:true,category:'Reserved decision',reason:'Public, financial, legal or access boundary'};if(p.breaking_change===true||p.meaning_change===true||p.permission_expansion===true)return{required:true,category:'Ontology or policy',reason:'Meaning or authority changes'};const issue=[p.evidence_state,p.conflict_state,p.validation_state,p.source_state].filter(Boolean).join(' ').toLowerCase();if((p.consequential===true||p.decision_critical===true)&&/conflict|contradict|unresolved|failed/.test(issue))return{required:true,category:'Evidence conflict',reason:'Consequential unresolved evidence'};const rights=[p.rights_state,p.permission_state,p.commercial_reuse,p.license_state].filter(Boolean).join(' ').toLowerCase();if(/unresolved|unknown|denied|expired|restricted/.test(rights)&&p.rights_question_resolved!==true)return{required:true,category:'Rights and legal',reason:'Reuse permission unresolved'};if(p.account_holder_action_required===true)return{required:true,category:'Account',reason:'Identity or consent required'};if(p.exact_artifact_publication_candidate===true)return{required:true,category:'Publication',reason:'Exact artifact ready'};return{required:false,category:'Automatic',reason:'Policy-routed and monitored'}}
function reviewList(){const routed=state.objects.filter(o=>['captured','proposed'].includes(o.status)).map(o=>({o,route:humanReviewRoute(o)})).filter(x=>x.route.required);const groups=Object.groupBy?Object.groupBy(routed,x=>x.route.category):routed.reduce((a,x)=>((a[x.route.category]||=[]).push(x),a),{});return heading('EXCEPTIONS, NOT DATA ENTRY','Decision inbox','Routine facts, concepts, analyses and drafts are audit-logged and flow automatically. Only unresolved consequential boundaries appear here.')+'<div class="callout">'+(routed.length?routed.length+' prepared decision'+(routed.length===1?'':'s')+' need human judgment.':'No human action is needed. The system continues monitored work automatically.')+'</div>'+Object.entries(groups).map(([category,items])=>'<section><div class="section-row"><h2>'+esc(category)+'</h2><span class="badge warning">'+items.length+' exception'+(items.length===1?'':'s')+'</span></div>'+items.map(({o,route})=>'<article class="review-item"><div><span class="eyebrow">'+esc(pretty(o.object_type))+'</span><h3>'+esc(o.title)+'</h3><p>'+esc(route.reason)+'. '+esc(o.payload.summary||o.purpose)+'</p></div><a href="'+recordLink(o)+'">Decide version '+o.version+' &rarr;</a></article>').join('')+'</section>').join('')+(routed.length?'':empty('The exception queue is clear','Routine records remain visible in object history, but they do not require approval.'))}
function sourcePage(){return heading('PERMISSION IS PART OF THE EVIDENCE','Sources & rights','Source access, factual reuse, imagery and automation each have their own recorded status.')+'<div class="grid two">'+objectsOf('source_policy').map(o=>'<article class="card"><div class="card-top"><span class="eyebrow">'+esc(o.payload.publisher)+'</span>'+badge(o.status)+'</div><h3>'+esc(o.title)+'</h3><p class="small">'+esc(o.payload.rights_basis)+'</p><p>'+link(o.payload.source_uri,'Open the original source')+'</p><div class="mini-fields"><div><span>Automated refresh</span>'+badge(o.payload.automation)+'</div><div><span>Commercial reuse</span>'+badge(o.payload.commercial_reuse)+'</div><div><span>Product photos</span>'+badge(o.payload.media_reuse)+'</div></div><p class="tiny muted">Observed '+date(o.payload.last_observed_at)+' / proposed cadence '+o.payload.refresh_days+' days</p><a class="small" href="'+recordLink(o)+'">Inspect policy record &rarr;</a></article>').join('')+'</div><div class="callout">Automatic collection is not running. Product imagery has not been imported. The initial facts are limited research observations with links to their originals.</div>'}
function commerce(){return heading('FROM USEFUL CONTENT TO A POSSIBLE PURCHASE','Revenue paths','Track the entire path to a payment. A shop or a possible partner program is not an active income stream.')+'<div class="grid two">'+objectsOf('commerce_path').map(o=>'<article class="card"><div class="eyebrow">'+esc(o.payload.customer_market)+'</div><h2>'+esc(o.title)+'</h2><p class="small">'+esc(o.payload.summary)+'</p><p>'+badge('neutral','Checkout '+o.payload.checkout)+' '+badge('warning','Publisher '+pretty(o.payload.publisher_access))+'</p><p class="small">'+link(o.payload.merchant_uri,'Merchant')+(o.payload.program_uri?' / '+link(o.payload.program_uri,'Program evidence'):'')+'</p><h3>What must still be resolved</h3><ul class="small muted">'+[...o.payload.purchase_friction,...o.payload.obligations].map(x=>'<li>'+esc(x)+'</li>').join('')+'</ul><p class="small">Commission: '+(o.payload.commission_rate==null?'Unknown':esc(o.payload.commission_rate*100)+'%')+'<br>Payment terms: '+esc(o.payload.payment_terms)+'</p><a class="small" href="'+recordLink(o)+'">Open the evidence record &rarr;</a></article>').join('')+'</div>'}
function learning(){return heading('FEEDBACK TO BETTER DECISIONS','Improve the engine.','Record intent, assess its scope, and prepare a change with a clear benefit and an evaluation.','<button data-action="new-feedback">Capture feedback</button>')+'<div class="grid two"><section><div class="section-row"><h2>Feedback</h2></div>'+objectsOf('feedback').map(o=>'<article class="card"><div class="eyebrow">'+esc(pretty(o.payload.classification))+'</div><h3>'+esc(o.title)+'</h3><p class="small">'+esc(o.payload.input)+'</p><p class="small muted">'+esc(o.payload.proposed_improvement)+'</p><div class="actions"><a href="'+recordLink(o)+'">History</a><button class="quiet" data-decision="'+esc(o.object_id)+'">Prepare a decision</button></div></article>').join('')+'</section><section><div class="section-row"><h2>Proposed decisions</h2></div>'+objectsOf('decision_record').map(o=>'<article class="card">'+badge(o.status)+'<h3>'+esc(o.title)+'</h3><p class="small">'+esc(o.payload.rationale)+'</p><p class="small"><strong>Evaluation:</strong> '+esc(o.payload.evaluation)+'</p><a href="'+recordLink(o)+'">Review decision &rarr;</a></article>').join('')+'</section></div>'}
function content(){return heading('ONE KNOWLEDGE BASE, DIFFERENT STORIES','Content studio','Select products in the catalogue, then compose a sourced 90-second brief. Publication and media clearance remain separate decisions.')+'<div class="callout">'+state.selected.size+' product(s) selected. These workflows produce draft briefs; changed-source and commercial stories require evidence that is not yet available.</div><div class="grid">'+state.workflows.map((w,i)=>'<article class="card workflow-card"><div class="workflow-number">'+String(i+1).padStart(2,'0')+'</div><h3>'+esc(w.label)+'</h3><p>'+esc(w.question)+'</p><span class="badge">'+(w.id==='change'||w.id==='commercial'?'Evidence gate outstanding':'Draft composer available')+'</span><br><button data-workflow="'+esc(w.id)+'" '+(['change','commercial'].includes(w.id)?'disabled':'')+'>Compose draft</button></article>').join('')+'</div><div class="section-row"><h2>Saved briefs</h2></div>'+objectsOf('content_brief').map(o=>'<article class="review-item"><div>'+badge(stale(o)?'warning':o.status,stale(o)?'Source changed':pretty(o.status))+'<h3>'+esc(o.title)+'</h3><p>'+esc(o.payload.summary)+'</p></div><a href="'+recordLink(o)+'">Read draft &rarr;</a></article>').join('')}
function definitions(){
 const objectEntries=Object.entries(state.objectTypes).sort(([a],[b])=>a.localeCompare(b));
 const actorMap=new Map();
 state.objects.forEach(o=>{const actor=o.created_by||'Not recorded';const item=actorMap.get(actor)||{count:0,types:new Set()};item.count+=1;item.types.add(o.object_type);actorMap.set(actor,item)});
 const objectRows=objectEntries.map(([name,schema])=>{const records=objectsOf(name);const columns=Object.keys(schema.properties||{});return '<tr><td><strong>'+esc(pretty(name))+'</strong><small>'+esc(name)+'</small></td><td>'+records.length+'<small>'+records.filter(o=>o.status==='active').length+' active</small></td><td>'+esc(columns.join(', ')||'Contract details unavailable')+'</td><td>'+esc(schema.description||schema.title||'Versioned governed object')+'</td></tr>'}).join('');
 const actorRows=[...actorMap.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([actor,item])=>'<tr><td><strong>'+esc(actor)+'</strong></td><td>'+item.count+'</td><td>'+esc([...item.types].sort().map(pretty).join(', '))+'</td><td>Observed writer identity<small>This records attribution; it does not prove a worker is currently running.</small></td></tr>').join('');
 const lifecycle=[
  ['Capture and curation','Create a versioned object, propose changes, retain evidence and attribute every write.','Object contract, validation, version history'],
  ['Evidence and rights','Keep source access, factual review, commercial reuse and media permission as separate checks.','Source policy and evidence gates'],
  ['Content production','Compose a source-linked brief, plan reusable scenes, render a private preview and retain exact lineage.','Brief, storyboard, recipe and render objects'],
  ['Feedback and evolution','Classify feedback, prepare a bounded decision, evaluate it, then promote or reject it without silently rewriting policy.','Feedback and decision records'],
  ['Release and publication','Require factual, rights, render-quality, spend and exact-artifact approval before any publisher receives credentials.','Release packet and human approval gate']
 ];
 return heading('SYSTEM CATALOGUE','System documentation','A live map of the governed datasets, object contracts, columns, actors, workflows and decision gates used by this workspace. Counts describe the current local store, not cloud deployment.','<button data-action="new-definition">Propose a field</button>')+
 '<nav class="doc-nav" aria-label="Documentation sections"><a href="#definitions-datasets">Datasets</a><a href="#definitions-columns">Columns</a><a href="#definitions-agents">Agents and actors</a><a href="#definitions-workflows">Workflows</a></nav>'+
 '<section class="stats documentation-stats"><div class="stat"><strong>'+state.objects.length+'</strong><span>Versioned records</span><small>Current local object snapshots</small></div><div class="stat"><strong>'+objectEntries.length+'</strong><span>Object contracts</span><small>Typed datasets available to the API</small></div><div class="stat"><strong>'+state.fields.length+'</strong><span>Semantic columns</span><small>Shared meanings and validation</small></div><div class="stat"><strong>'+state.workflows.length+'</strong><span>Content workflows</span><small>Loaded workflow families</small></div></section>'+
 '<section id="definitions-datasets" class="catalog-section"><div class="section-row"><div><div class="eyebrow">01 / DATASETS AND OBJECTS</div><h2>What the system stores</h2></div><p class="small muted">Each row below is an API-exposed payload contract. Records remain versioned objects with purpose, evidence, review state and history.</p></div><div class="table-wrap"><table><thead><tr><th>Dataset / object type</th><th>Current records</th><th>Defined payload columns</th><th>Contract purpose</th></tr></thead><tbody>'+objectRows+'</tbody></table></div></section>'+
 '<section id="definitions-columns" class="catalog-section"><div class="section-row"><div><div class="eyebrow">02 / SEMANTIC LAYER</div><h2>Columns and shared meanings</h2></div><p class="small muted">Product forms and comparisons use these governed concepts. Unknown remains distinct from false, and new concepts require reviewed promotion.</p></div><div class="table-wrap"><table><thead><tr><th>Column / concept</th><th>Meaning</th><th>Type / unit</th><th>Applies to</th></tr></thead><tbody>'+state.fields.map(f=>'<tr><td><strong>'+esc(f.label)+'</strong><small>'+esc(f.key)+'</small></td><td>'+esc(f.description)+'</td><td>'+esc(f.value_type)+(f.unit?' / '+esc(f.unit):'')+'</td><td>'+esc(pretty(f.category))+'</td></tr>').join('')+'</tbody></table></div></section>'+
 '<section id="definitions-agents" class="catalog-section"><div class="section-row"><div><div class="eyebrow">03 / AGENTS AND ACTORS</div><h2>Who has written to the knowledge base</h2></div><p class="small muted">These identities come from current object attribution. Agent profiles and permissions remain governed objects; attribution is not a live-process monitor.</p></div>'+(actorRows?'<div class="table-wrap"><table><thead><tr><th>Actor identity</th><th>Records</th><th>Object types written</th><th>Meaning</th></tr></thead><tbody>'+actorRows+'</tbody></table></div>':empty('No attributed writers','No current object contains a writer identity.'))+'</section>'+
 '<section id="definitions-workflows" class="catalog-section"><div class="section-row"><div><div class="eyebrow">04 / WORKFLOWS AND GATES</div><h2>How work moves through the system</h2></div><p class="small muted">A workflow may prepare an artifact, but it cannot substitute for evidence, rights, cost or publication approval.</p></div><div class="grid workflow-doc-grid">'+lifecycle.map(([title,body,output])=>'<article class="card"><h3>'+esc(title)+'</h3><p class="small">'+esc(body)+'</p><span class="badge neutral">'+esc(output)+'</span></article>').join('')+'</div><div class="section-row"><h2>Content workflow catalogue</h2><span class="small muted">'+state.workflows.length+' loaded families</span></div><div class="table-wrap"><table><thead><tr><th>Workflow</th><th>Question answered</th><th>Minimum inputs</th><th>Current boundary</th></tr></thead><tbody>'+state.workflows.map(w=>'<tr><td><strong>'+esc(w.label)+'</strong><small>'+esc(w.id)+'</small></td><td>'+esc(w.question)+'</td><td>'+esc(w.minimum_products)+' product'+(w.minimum_products===1?'':'s')+'</td><td>'+(['change','commercial'].includes(w.id)?badge('warning','Additional evidence gate'):badge('active','Draft composer available'))+'</td></tr>').join('')+'</tbody></table></div><div class="callout">Documentation is generated from the current API schema and local object store. BigQuery tables, Firestore resources or agent profiles count as operational only when their connected runtime state is separately verified.</div></section>';
}
async function detail(id){const o=get(id)||await api('/objects/'+encodeURIComponent(id));const history=await api('/objects/'+encodeURIComponent(id)+'/history');
 let body='';
 if(o.object_type==='product')body='<div class="table-wrap"><table><thead><tr><th>Field</th><th>Recorded value</th></tr></thead><tbody>'+state.fields.filter(f=>f.category==='all'||f.category===o.payload.category).map(f=>{const a=o.payload.fields?.[f.key];return '<tr><td>'+esc(f.label)+'<small>'+esc(f.description)+'</small></td><td>'+esc(valueText(a))+(a?.value!=null?' '+esc(f.unit||''):'')+'<small>'+esc(a?.conditions||'No supported value recorded')+'</small></td></tr>'}).join('')+'</tbody></table></div>';
 else if(o.object_type==='content_brief')body='<article class="card"><div class="eyebrow">'+esc(o.payload.workflow_family||'Research brief')+' / '+esc(o.payload.duration_seconds||'90')+' SECONDS</div><h2>'+esc(o.payload.presentation?.hook||o.title)+'</h2><p>'+esc(o.payload.summary)+'</p>'+((o.payload.presentation?.sections||[]).map(s=>'<h3>'+esc(s.heading)+'</h3><p class="small">'+esc(s.objective)+'</p>')).join('')+'<h3>Claim ledger</h3><ul class="small">'+(o.payload.claims||[]).map(c=>'<li>'+esc(c.statement)+' <span class="muted">'+esc(pretty(c.evidence_tier))+' / '+esc(c.confidence==null?'Confidence not assessed':'Recorded confidence: '+c.confidence)+' / '+esc((c.caveats||[]).join(' '))+'</span></li>').join('')+'</ul></article>';
 else if(o.object_type==='storyboard')body=window.WorkspaceProduction.render(o);
 else body='<article class="card">'+Object.entries(o.payload).map(([k,v])=>'<h3>'+esc(pretty(k))+'</h3><p class="small">'+esc(typeof v==='object'?JSON.stringify(v,null,2):v)+'</p>').join('')+'</article>';
 const previous=history.length>1?history[history.length-2].snapshot:null;
 const diff=previous?Object.keys(o.payload).filter(k=>JSON.stringify(o.payload[k])!==JSON.stringify(previous.payload[k])):[];
 return '<a class="back" href="#'+(o.object_type==='product'?'catalogue':'review')+'">&larr; Back to workspace</a>'+heading(pretty(o.object_type)+' / VERSION '+o.version,o.title,o.payload.summary||o.purpose,o.object_type==='product'?'<button data-edit="'+esc(o.object_id)+'">Propose changes</button>':'')+
 '<div class="detail-grid"><section class="stack">'+(stale(o)?'<div class="callout">An input product has changed. Rebuild this draft before approval.</div>':'')+(diff.length?'<div class="diff">Changed since the previous version: '+esc(diff.map(pretty).join(', '))+'. Full snapshots are retained in history below.</div>':'')+body+
 '<article class="card"><h3>Version history</h3><ul class="timeline">'+history.map(h=>'<li><strong>Version '+h.snapshot.version+' / '+esc(h.event.event_type)+'</strong><small>'+esc(h.event.actor_id)+' ('+esc(h.event.actor_type)+') / '+date(h.event.occurred_at)+'</small><details><summary>Inspect this snapshot</summary><pre>'+esc(JSON.stringify(h.snapshot.payload,null,2))+'</pre></details></li>').join('')+'</ul></article></section><aside class="stack"><article class="card"><div class="eyebrow">DECISION STATUS</div><p>'+badge(o.status)+'</p><p class="small muted">A decision applies to version '+o.version+'. Approval does not publish this record or authorize external spending.</p>'+
 (humanReviewRoute(o).required&&['captured','proposed'].includes(o.status)&&state.session.role==='reviewer'?'<label class="small">Decision notes<textarea id="review-notes" rows="3"></textarea></label><div class="actions"><button data-review="approved" data-object="'+esc(o.object_id)+'" '+(stale(o)?'disabled':'')+'>Approve exception</button><button class="quiet" data-review="changes_requested" data-object="'+esc(o.object_id)+'">Needs changes</button><button class="danger" data-review="rejected" data-object="'+esc(o.object_id)+'">Reject</button></div>':'<p class="small">Human action: '+esc(humanReviewRoute(o).required?(o.review.reviewed_by||'Decision pending'):'Not required; policy-routed and monitored')+'</p>')+'</article><article class="card"><h3>Original sources</h3>'+sourcesHTML(o)+'</article><article class="card"><h3>Context and limits</h3><p class="small">'+esc(o.payload.variant||'')+'</p><p class="small muted">'+esc((o.payload.caveats||[]).join(' ')||o.purpose)+'</p></article></aside></div>';
}
let renderSequence=0;
async function render(){
 const seq=++renderSequence;const [page='overview',id]=location.hash.slice(1).split('/');
 document.querySelectorAll('nav a').forEach(a=>a.classList.toggle('active',a.dataset.nav===page));
 const screens={overview,catalogue,compare,review:()=>window.WorkspaceProduction.reviewInbox(),sources:()=>window.WorkspaceProduction.sourcePage(),content:()=>window.WorkspaceProduction.contentStudio()+content(),learning,commerce,definitions};
 try{const markup=page==='object'?await detail(decodeURIComponent(id||'')):await (screens[page]||overview)();if(seq===renderSequence){main.innerHTML='<div class="reveal">'+markup+'</div>';document.title=(page==='object'?get(decodeURIComponent(id))?.title||'Record':pretty(page))+' / SmartGlasses'}}
 catch(e){main.innerHTML=empty('Could not open this view',e.message)}
}
function input(label,name,value='',type='text',required=false){return '<label>'+esc(label)+'<input name="'+esc(name)+'" type="'+type+'" value="'+esc(value)+'" '+(type==='number'?'step="any" ':'')+(required?'required':'')+'></label>'}
function textArea(label,name,value='',required=false){return '<label class="full">'+esc(label)+'<textarea name="'+esc(name)+'" '+(required?'required':'')+'>'+esc(value)+'</textarea></label>'}
function select(label,name,values,value){return '<label>'+esc(label)+'<select name="'+esc(name)+'">'+values.map(v=>'<option value="'+esc(v)+'" '+(v===value?'selected':'')+'>'+esc(pretty(v))+'</option>').join('')+'</select></label>'}
function openForm(title,markup,handler){document.querySelector('#editor-body').innerHTML='<h2>'+esc(title)+'</h2><form class="editor-form"><p class="small muted">Saved as a proposal with history. Credentials do not belong in these forms.</p>'+markup+'<div class="error-box" role="alert"></div><button type="submit">Save proposal</button></form>';dialog.showModal();dialog.querySelector('.editor-form').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget;const btn=form.querySelector('[type=submit]');btn.disabled=true;try{await handler(new FormData(form));dialog.close();await reload();toast('Proposal saved with its history.')}catch(error){form.querySelector('.error-box').textContent=error.message}finally{btn.disabled=false}}}
async function capture(object){return api('/objects',{method:'POST',headers:{'Idempotency-Key':key()},body:JSON.stringify(object)})}
window.WorkspaceProduction.configure({api,reload,state});
function buildEvidenceFields(form,definitions,previous,newSourceId,hasNewSource){
 const fields={};
 for(const f of definitions){
  if(!['all',form.get('category')].includes(f.category))continue;
  const old=previous[f.key];const raw=String(form.get(f.key)??'').trim();
  const value=raw===''?null:f.value_type==='number'?Number(raw):f.value_type==='boolean'?raw==='true':raw;
  if(f.value_type==='number'&&value!==null&&!Number.isFinite(value))throw new Error(f.label+' requires a finite number.');
  const chosen=form.getAll(f.key+'_source').filter(Boolean);
  if(chosen.includes('new')&&!hasNewSource)throw new Error('Enter the additional source URL before selecting it.');
  const refs=[...new Set(chosen.map(id=>id==='new'?newSourceId:id))];
  const conditions=String(form.get(f.key+'_conditions')||'');
  if(value===null&&!old&&!refs.length&&!conditions)continue;
  if(value!==null&&!refs.length)throw new Error(f.label+' needs at least one evidence source.');
  const observed=String(form.get(f.key+'_observed_at')||'').trim();
  if(!observed||!Number.isFinite(Date.parse(observed))||!/(Z|[+-]\d{2}:\d{2})$/i.test(observed))throw new Error(f.label+' needs an observation time with a timezone.');
  const confidenceText=String(form.get(f.key+'_confidence')??'').trim();
  const confidence=confidenceText===''?null:Number(confidenceText);
  if(confidence!==null&&(!Number.isFinite(confidence)||confidence<0||confidence>1))throw new Error(f.label+' confidence must be blank or between 0 and 1.');
  fields[f.key]={...old,value,source_ids:refs,conditions,observed_at:observed,confidence,
   evidence_kind:form.get(f.key+'_kind')||old?.evidence_kind||'manufacturer_stated'};
 }
 return fields;
}
function editProduct(id){const o=id?get(id):null;const p=o?.payload||{brand:'',category:'display',market:'',variant:'',buyer_job:'',summary:'',fields:{}};
 const openedAt=new Date().toISOString();
 let markup='<div class="form-grid">'+input('Product name','title',o?.title||'','text',true)+input('Brand','brand',p.brand,'text',true)+select('Category','category',['display','camera_audio','ar'],p.category)+input('Market / source scope','market',p.market,'text',true)+input('Exact variant','variant',p.variant,'text',true)+input('Buyer job','buyer_job',p.buyer_job,'text',true)+textArea('Research summary','summary',p.summary,true)+input('Additional source URL (optional)','source_uri','','url')+'</div>';
 markup+='<p class="small muted">Unchanged fields retain their observation dates and confidence. Update an observation date only when evidence was actually re-observed. New fields show the current time: correct it if the evidence is older. Leave confidence blank when unassessed. Select multiple sources with Command/Ctrl.</p>'+state.fields.map(f=>{const a=p.fields?.[f.key];const kind=f.value_type;return '<details class="field-edit" '+(a?.value!=null?'open':'')+'><summary>'+esc(f.label)+(f.unit?' ('+esc(f.unit)+')':'')+'</summary><p>'+esc(f.description)+'</p><div class="form-grid">'+(kind==='boolean'?select('Value',f.key,['','true','false'],a?.value==null?'':String(a.value)):input('Value',f.key,a?.value??'',kind==='number'?'number':'text'))+'<label>Evidence sources<select multiple name="'+esc(f.key)+'_source">'+((o?.sources||[]).map(s=>'<option value="'+esc(s.source_id)+'" '+(a?.source_ids?.includes(s.source_id)?'selected':'')+'>'+esc(s.title||s.publisher||s.uri)+'</option>')).join('')+'<option value="new">Additional source URL above</option></select></label>'+input('Conditions / limitations',f.key+'_conditions',a?.conditions||'')+select('Recorded evidence type',f.key+'_kind',['manufacturer_stated','independent_test','human_observation','inference'],a?.evidence_kind||'manufacturer_stated')+input('Observation time (ISO format, with timezone)',f.key+'_observed_at',a?.observed_at||openedAt)+input('Confidence (0-1; blank if unassessed)',f.key+'_confidence',a?.confidence??'','number')+'</div></details>'}).join('');
 openForm(o?'Propose product changes':'Capture a product',markup,async form=>{
  const sources=[...(o?.sources||[])];const uri=String(form.get('source_uri')||'').trim();
  const existing=sources.find(s=>s.uri===uri);const newId=existing?.source_id||'src_'+key();
  if(uri&&!existing)sources.push({source_id:newId,uri,title:'Additional research source',captured_at:new Date().toISOString()});
  const fields=buildEvidenceFields(form,state.fields,p.fields||{},newId,Boolean(uri));
  const payload={...p,brand:form.get('brand'),category:form.get('category'),market:form.get('market'),variant:form.get('variant'),buyer_job:form.get('buyer_job'),summary:form.get('summary'),fields};
  if(o)return api('/objects/'+encodeURIComponent(id)+'/curate',{method:'POST',headers:{'Idempotency-Key':key()},body:JSON.stringify({expected_version:o.version,patch:{title:form.get('title'),payload,sources}})});
  return capture({object_type:'product',title:form.get('title'),purpose:'Preserve source-linked product evidence for online buyers.',sources,payload});
 });
}
function feedbackForm(){openForm('Capture useful feedback',input('Title','title','','text',true)+select('Kind','classification',['preference','correction','operating_directive','hypothesis','ontology_gap'],'correction')+textArea('Your input','input','',true)+textArea('Possible reusable improvement','improvement'),f=>capture({object_type:'feedback',title:f.get('title'),purpose:'Capture human context without promoting it directly to a fact or policy.',payload:{summary:f.get('title'),input:f.get('input'),classification:f.get('classification'),proposed_improvement:f.get('improvement')}}))}
function decisionForm(id){openForm('Prepare a decision',input('Title','title','','text',true)+select('Disposition','disposition',['proposed','no_change','deferred'],'proposed')+textArea('Reasoning and evidence','rationale','',true)+textArea('Expected benefit','benefit','',true)+textArea('How to evaluate the improvement','evaluation','',true),f=>capture({object_type:'decision_record',title:f.get('title'),purpose:'Evaluate a scoped improvement without silently changing runtime policy.',parent_ids:[id],payload:{summary:f.get('title'),feedback_ids:[id],disposition:f.get('disposition'),rationale:f.get('rationale'),expected_benefit:f.get('benefit'),evaluation:f.get('evaluation')}}))}
function definitionForm(){openForm('Propose a new field','<div class="form-grid">'+input('Stable key (example: cable_length_m)','key','','text',true)+input('Readable label','label','','text',true)+select('Value type','value_type',['number','text','boolean'],'text')+input('Unit (optional)','unit')+select('Applicable category','category',['all','display','camera_audio','ar'],'all')+textArea('Meaning and comparison limits','description','',true)+'</div>',f=>capture({object_type:'field_definition',title:f.get('label'),purpose:'Add a reusable field to metadata-driven product forms after review.',payload:{key:f.get('key'),label:f.get('label'),value_type:f.get('value_type'),unit:f.get('unit')||null,category:f.get('category'),description:f.get('description')}}))}
document.addEventListener('click',async event=>{const button=event.target.closest('button');if(!button)return;try{
 if(button.id==='refresh'){await reload();toast('Workspace refreshed.');return;}
 if(button.dataset.action==='new-product')return editProduct();
 if(button.dataset.action==='new-feedback')return feedbackForm();
 if(button.dataset.action==='new-definition')return definitionForm();
 if(button.dataset.edit)return editProduct(button.dataset.edit);
 if(button.dataset.decision)return decisionForm(button.dataset.decision);
 if(button.dataset.review){const o=get(button.dataset.object);button.disabled=true;await api('/objects/'+encodeURIComponent(o.object_id)+'/review',{method:'POST',headers:{'Idempotency-Key':key()},body:JSON.stringify({expected_version:o.version,decision:button.dataset.review,notes:document.querySelector('#review-notes')?.value||null})});await reload();toast('Review saved.');}
 if(button.dataset.workflow){button.disabled=true;const o=await api('/content/briefs',{method:'POST',headers:{'Idempotency-Key':key()},body:JSON.stringify({family:button.dataset.workflow,product_ids:[...state.selected]})});await reload();location.hash=recordLink(o);toast('Sourced draft prepared.');}
 }catch(e){toast(e.message,true)}finally{button.disabled=false}});
document.addEventListener('change',e=>{if(e.target.dataset.compare){const id=e.target.dataset.compare;if(e.target.checked){if(state.selected.size>=4){e.target.checked=false;toast('Choose up to four products.',true);return;}state.selected.add(id)}else state.selected.delete(id)}});
document.addEventListener('input',e=>{if(e.target.id==='catalogue-search'){state.search=e.target.value;document.querySelector('#product-grid').innerHTML=products().filter(p=>JSON.stringify([p.title,p.payload.brand,p.payload.buyer_job]).toLowerCase().includes(state.search.toLowerCase())).map(productCard).join('')}});
window.addEventListener('hashchange',render);
async function start(){try{state.session=await api('/session');document.querySelector('#session-label').textContent=state.session.mode==='local_operator'?'Local operator session':state.session.role+' session';await reload()}catch(e){main.innerHTML=heading('PRIVATE ACCESS','Connect to your workspace.','Enter a scoped access token only in this local form. It stays in browser memory for this session.')+'<form id="login" class="card">'+input('Access token','token','','password',true)+'<p><button>Connect</button></p><div class="error-box">'+esc(e.message)+'</div></form>';document.querySelector('#login').onsubmit=async event=>{event.preventDefault();state.token=new FormData(event.currentTarget).get('token');await start()}}}
start();
