(() => {
  const nativeFetch = window.fetch.bind(window);
  let config;
  let user;
  let resolveReady;
  const ready = new Promise(resolve => { resolveReady = resolve; });

  const escape = value => String(value || '').replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  const load = src => new Promise((resolve, reject) => { const script = document.createElement('script'); script.src = src; script.onload = resolve; script.onerror = () => reject(new Error('Google authentication library could not be loaded.')); document.head.appendChild(script); });
  function loginPanel(message = '') { let panel = document.querySelector('#adminLogin'); if (!panel) { panel = document.createElement('section'); panel.id = 'adminLogin'; panel.className = 'admin-login'; panel.innerHTML = '<div class="admin-login__card"><p>SOLO OPERATOR ACCESS</p><h1>Sign in as an approved administrator</h1><p>Google verifies your identity. Access is granted only when the verified email is enabled in the local administrator allowlist.</p><button type="button" id="googleAdminLogin">Continue with Google</button><button type="button" id="copyAdminLoginUrl" class="quiet" hidden>Copy Chrome login address</button><div id="adminLoginStatus" role="status"></div></div>'; document.body.appendChild(panel); } panel.querySelector('#adminLoginStatus').textContent = message; const copy = panel.querySelector('#copyAdminLoginUrl'); copy.onclick = async () => { try { await navigator.clipboard.writeText(location.href); panel.querySelector('#adminLoginStatus').textContent = 'Address copied. Open Google Chrome, paste it into the address bar, and continue with Google there.'; } catch { panel.querySelector('#adminLoginStatus').textContent = `Open this address in Google Chrome: ${location.href}`; } }; return panel; }
  async function validate(current) { const token = await current.getIdToken(); const response = await nativeFetch('/v1/session', {headers:{Authorization:'Bearer ' + token}}); if (!response.ok) { const data = await response.json().catch(() => ({})); throw new Error(data.detail || 'This account is not authorized.'); } return token; }
  function identity(current) { document.querySelector('#adminLogin')?.remove(); const masthead = document.querySelector('.masthead'); if (!masthead || document.querySelector('#adminIdentity')) return; const node = document.createElement('div'); node.id = 'adminIdentity'; node.className = 'admin-identity'; node.innerHTML = `<span>${escape(current.email || 'Verified administrator')}</span><button type="button">Sign out</button>`; node.querySelector('button').onclick = () => firebase.auth().signOut(); masthead.appendChild(node); }
  window.fetch = async (input, init = {}) => { const url = typeof input === 'string' ? input : input.url; if (!url.includes('/v1/') || url.includes('/v1/admin-auth/config')) return nativeFetch(input, init); await ready; if (!config?.required) return nativeFetch(input, init); if (!user) throw new Error('Administrator sign-in is required.'); const token = await user.getIdToken(); const headers = new Headers(init.headers || (typeof input === 'string' ? undefined : input.headers)); headers.set('Authorization', 'Bearer ' + token); return nativeFetch(input, {...init, headers}); };
  async function start() { config = await (await nativeFetch('/v1/admin-auth/config')).json(); if (!config.required) { resolveReady(); return; } if (!config.configured) { const panel = loginPanel('Add an administrator and Firebase web configuration before enforcing sign-in.'); panel.querySelector('button').disabled = true; return; } await load('/operator/vendor/firebase-app-compat.js'); await load('/operator/vendor/firebase-auth-compat.js'); if (!firebase.apps.length) firebase.initializeApp(config.firebase); firebase.auth().onAuthStateChanged(async current => { if (!current) { user = null; const panel = loginPanel(); panel.querySelector('button').onclick = async () => { try { panel.querySelector('#copyAdminLoginUrl').hidden = true; panel.querySelector('#adminLoginStatus').textContent = 'Opening Google sign-in...'; await firebase.auth().signInWithPopup(new firebase.auth.GoogleAuthProvider()); } catch (error) { const embeddedBlocked = ['auth/internal-error','auth/popup-blocked','auth/operation-not-supported-in-this-environment'].includes(error.code); panel.querySelector('#copyAdminLoginUrl').hidden = !embeddedBlocked; panel.querySelector('#adminLoginStatus').textContent = embeddedBlocked ? 'This embedded browser blocked Google sign-in. Copy the address and open it in Google Chrome to finish authentication.' : error.message; } }; return; } try { await validate(current); user = current; identity(current); resolveReady(); } catch (error) { await firebase.auth().signOut(); loginPanel(error.message); } }); }
  start().catch(error => { const panel = loginPanel(error.message); panel.querySelector('button').disabled = true; });
})();
